theme: jekyll-theme-minimal
logo: [Location of the logo]
show_downloads: True
# google_analytics: [Your Google Analytics tracking ID]
title: Anil Ayal's Portfolio
description: Showcase of Projects / Works
