theme: jekyll-theme-minimal
logo: https://anilayal.com/logo.png
# show_downloads: True
# google_analytics: [Your Google Analytics tracking ID]
title: [Anil Ayal's Portfolio]
description: [Showcase of Projects / Works]
